# Generated by Django 2.2.6 on 2019-10-05 13:16

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='address',
            field=django_google_maps.fields.AddressField(default='128 Pennington Ave', max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='1', max_length=100),
        ),
    ]
