# Generated by Django 2.2.6 on 2019-10-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20191005_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='geolocation',
        ),
    ]
