# Generated by Django 2.2.6 on 2019-10-05 13:25

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_comment_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='1', max_length=100),
        ),
    ]
