# Generated by Django 2.2.6 on 2019-10-05 13:29

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_comment_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='address',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='', max_length=100),
        ),
    ]
