# Generated by Django 2.2.6 on 2019-10-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20191005_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='geolocation',
        ),
    ]
