# Generated by Django 2.2.6 on 2019-10-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20191005_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='events.Category'),
        ),
    ]
